### GET request to example server
GET http://localhost:8080/api/ai/words?
    topic=food&
    difficulty=5&
    nQuestions=20

###

GET http://localhost:8080/api/ai/sentences?
    topic=sport&
    difficulty=4&
    nQuestions=50

###
POST http://localhost:8080/api/batch/generate?
    totalQuestions=100&
    batchSize=20&
    delayMs=3000

###

GET http://localhost:8080/api/batch/status
