### GET request to example server
GET http://localhost:8080/api/ai/words?
    topic=food&
    level=5&
    nQuestions=20

###

GET http://localhost:8080/api/ai/sentences?
    topic=sport&
    level=4&
    nQuestions=5

###
POST http://localhost:8080/api/ai/batch-generate?
    totalQuestions={{$random.integer(100)}}&
    batchSize={{$random.integer(100)}}&
    delayMs={{$random.integer(100)}}

###

GET http://localhost:8080/api/batch/batch-status
